name: HTMLSelecter
description: Simple jQuery like selecter.
version: 1.0.0
# homepage: https://www.example.com
author: Štěpán Martínek <ste.martinek@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  html: any

dev_dependencies:
  test: ^1.0.0
